[[pairs]]
name = "*"

[[pairs.intervals]]
monitors = [
    # "touch:close,ema,5",
    "touch:close,ema,20",
    "touch:close,ema,60",
    "touch:close,ema,80",
    # "touch:close,ema,200",
    "touch:close,ema,240",

    "cross:close,ema,5,20",
    "cross:close,ema,20,60",
    "cross:close,ema,20,80",
    "cross:close,ema,80,240",

    "hold:close,ema,20,3",
    "hold:close,ema,60,3",
    "hold:close,ema,80,3",
    # "hold:close,ema,200,3",
    "hold:close,ema,240,3",

    # "rate:qty,ema,20,abs,>,1.5",
    # "rate:qty,ema,20,abs,<,0.4",

    "fbq:20,0.4/1.2,0.4/1.2,0.4/1.5",

    # "bb:20,2",
    "macd:12,26,9",

    "shadow:0.5",

    # "read:close,ema,5,20,60,80,200,240",
    # qty
    # "cross:qty,ema,5,20",
    # "hold:qty,ema,20,3",
]
reads = [5, 20, 60, 80, 240]

[[pairs.intervals]]
name = "3m"
monitors = [
    # "touch:close,ema,200",
    "touch:close,ema,80",
    "touch:close,ema,240",

    "cross:close,ema,20,60",
    "cross:close,ema,20,80",
    "cross:close,ema,80,240",

    "hold:close,ema,60,3",
    "hold:close,ema,80,3",
    "hold:close,ema,240,3",

    "shadow:0.7",

    "fbq:20,0.2/1.5,0.2/1.5,0.2/1.8",

    # "rate:qty,ema,20,abs,>,2.0",
    # "rate:qty,ema,20,abs,>,4.0",
    # "rate:qty,ema,20,abs,<,0.3",

    # "pdiff:temp,0.15",
    # "pdiff:perm,0.15",
]
reads = [5, 20, 60, 80, 240]
no_wildcard = true

[[pairs.intervals]]
name = "15m"
# monitors = [
#     "pdiff:temp,0.5",
#     "pdiff:perm,0.5",
# ]

[[pairs.intervals]]
name = "1h"
monitors = [
    # "pdiff:perm,1.5",
    "touch:close,ema,5",
]

[[pairs.intervals]]
name = "4h"
monitors = [
    # "pdiff:perm,2.5",
    "touch:close,ema,5",
]

[[pairs.intervals]]
name = "1d"
monitors = [
    # "pdiff:perm,5.0",
    "touch:close,ema,5",
]

[[pairs]]
name = "ethusdt"

# [[pairs]]
# name = "btcusdt"

[[notify]]
type = "Cmd"
bin = ""
args = [
    "-s",
    "$title",
    "-b",
    "$body",
    "-t",
    "10s",
]

[[notify]]
type = "DingTalk"
token = ""
secret = ""
