[[pairs]]
name = "*"

[[pairs.intervals]]
monitors = [
    "touch:close,ema,5,0.5",
    "touch:close,ema,20,0.4",
    "touch:close,ema,60",
    "touch:close,ema,80",
    "touch:close,ema,240",

    "cross:close,ema,5,20",
    "cross:close,ema,20,60",
    "cross:close,ema,20,80",
    "cross:close,ema,80,240",

    "hold:close,ema,20,3",
    "hold:close,ema,60,3",
    "hold:close,ema,80,3",
    "hold:close,ema,240,3",

    "fbq:20,0.3/1.2,0.3/1.2,0.3/1.5",

    "macd:12,26,9",

    "shadow:0.5,0.4",
]
reads = [5, 20, 60, 80, 240]

[[pairs.intervals]]
name = "3m"
monitors = [
    "touch:close,ema,20,0.6",
    "touch:close,ema,60,0.4",
    "touch:close,ema,80,0.4",
    "touch:close,ema,240,0.4",

    "cross:close,ema,20,60",
    "cross:close,ema,20,80",
    "cross:close,ema,80,240",

    "hold:close,ema,60,3",
    "hold:close,ema,80,3",
    "hold:close,ema,240,3",

    "fbq:20,0.2/1.8,0.0/1.8,0.2/1.8",
]
reads = [5, 20, 60, 80, 240]
no_wildcard = true

[[pairs.intervals]]
name = "15m"

[[pairs.intervals]]
name = "1h"

[[pairs.intervals]]
name = "4h"

[[pairs.intervals]]
name = "1d"

[[pairs]]
name = "ethusdt"

[[pairs]]
name = "btcusdt"

[[notify]]
type = "Cmd"
bin = ""
args = [
    "-s",
    "$title",
    "-b",
    "$body",
    "-t",
    "10s",
]

[[notify]]
type = "DingTalk"
token = ""
secret = ""
