[[pairs]]
name = "*"

[[pairs.intervals]]
monitors = [
    "cross2:close,ema,5,20,60",
    "cross2:close,ema,5,60,200",

    "hold2:ema,5,5",
    "hold2:ema,20,3",
    "hold2:ema,60,3",
    "hold2:ema,200,3",

    "fbq:20,1,0.2/1.5,0.2/1.5,0.2/1.8",

    "macd:12,26,9",

    # "shadow:0.6,0.5",
]
reads = [5, 20, 60, 200]

[[pairs.intervals]]
name = "1m"
monitors = [
    "ma-seq:ema,[20,60,200]/30@120,true",
]
no_wildcard = true

[[pairs.intervals]]
name = "3m"
monitors = [
    "hold2:ema,20,5",
    "hold2:ema,60,5",
    "hold2:ema,200,5",

    "fbq:20,2,0.2/2.0,0.0/2.0,0.2/3.0",

    # "shadow:0.7,1.2",

    "ma-seq:ema,[5,20,60]/5@20,false",
    "ma-seq:ema,[20,60,200]/5@20,true",
]
no_wildcard = true

[[pairs.intervals]]
name = "15m"
monitors = [
    "hold2:ema,20,5",
    "hold2:ema,60,5",
    "hold2:ema,200,5",

    "fbq:20,1,0.2/1.8,0.2/1.8,0.2/2.0",

    # "shadow:0.6,0.8",

    "ma-seq:ema,[5,20,60]/4@8,true",
]
no_wildcard = true
reads = [5, 20, 60, 200]

[[pairs.intervals]]
name = "1h"
monitors = [
    "ma-seq:ema,[5,20,60]/4@4,true",
]

[[pairs.intervals]]
name = "4h"
monitors = [
    "ma-seq:ema,[5,20,60]/4@4,true",
]

[[pairs.intervals]]
name = "1d"

[[pairs.intervals]]
name = "3d"

[[pairs.intervals]]
name = "1w"

# [[pairs]]
# name = "ethusdt"

[[pairs]]
name = "btcusdt"

[[notify]]
type = "Cmd"
bin = ""
args = [
    "-s",
    "$title",
    "-b",
    "$body",
    "-t",
    "10s",
]

[[notify]]
type = "DingTalk"
token = ""
secret = ""
